package com.mycompany.gamefootball;
import java.util.Random;
import java.util.ArrayList;
import java.util.List;

public class Nomes {
    Random random = new Random();
    private List<String> lista_de_nomes(){
        List<String> nomes = new ArrayList<>();
        nomes.add("André");
        nomes.add("Alexandre");
        nomes.add("Arthur");
        nomes.add("Alvaro");
        nomes.add("Antonio");
        nomes.add("Abner");
        nomes.add("Anderson");
        nomes.add("Alessandro");
        nomes.add("Adamastor");
        nomes.add("Agamenon");
        nomes.add("Adenor");
        nomes.add("Aldair");
        nomes.add("Amir");
        nomes.add("Almir");
        nomes.add("Ailton");
        nomes.add("Airton");
        nomes.add("Alberto");
        nomes.add("Angelo");
        nomes.add("Adenilton");
        nomes.add("Adenilson");
        nomes.add("Agenor");
        nomes.add("Agessandro");
        nomes.add("Afonso");
        nomes.add("Alaor");
        nomes.add("Bruno");
        nomes.add("Bernardo");
        nomes.add("Braian");
        nomes.add("Breno");
        nomes.add("Bento");
        nomes.add("Bartolomeu");
        nomes.add("Barão");
        nomes.add("Braulio");
        nomes.add("Benjamin");
        nomes.add("Benício");
        nomes.add("Benedito");
        nomes.add("Benedetto");
        nomes.add("Belchior");
        nomes.add("Boris");
        nomes.add("Basílio");
        nomes.add("Baltazar");
        nomes.add("Berilo");
        nomes.add("Cauan");
        nomes.add("Carlos");
        nomes.add("Caique");
        nomes.add("Caio");
        nomes.add("César");
        nomes.add("Célio");
        nomes.add("Celso");
        nomes.add("Cícero");
        nomes.add("Calvin");
        nomes.add("Carlton");
        nomes.add("Charles");
        nomes.add("Chandler");
        nomes.add("Chester");
        nomes.add("Chury");
        nomes.add("Cornelius");
        nomes.add("Candido");
        nomes.add("Daniel");
        nomes.add("Danilo");
        nomes.add("Denilson");
        nomes.add("Denner");
        nomes.add("Diego");
        nomes.add("Diogo");
        nomes.add("Dionísio");
        nomes.add("Dalesandro");
        nomes.add("Drauzio");
        nomes.add("Denzel");
        nomes.add("Erick");
        nomes.add("Endrick");
        nomes.add("Enzo");
        nomes.add("Eduardo");
        nomes.add("Elano");
        nomes.add("Enrico");
        nomes.add("Felipe");
        nomes.add("Felicio");
        nomes.add("Fernando");
        nomes.add("Filipe");
        nomes.add("Filipo");
        nomes.add("Foster");
        nomes.add("Francisco");
        nomes.add("Fabiano");
        nomes.add("Fabricio");
        nomes.add("Fabio");
        nomes.add("Fausto");
        nomes.add("Fagner");
        nomes.add("Fabner");
        nomes.add("Firmino");
        nomes.add("Gabriel");
        nomes.add("Gustavo");
        nomes.add("Guilherme");
        nomes.add("Geraldo");
        nomes.add("Gerson");
        nomes.add("Henrique");
        nomes.add("Homero");
        nomes.add("Herculano");
        nomes.add("Hermes");
        nomes.add("Heraldo");
        nomes.add("Iuri");
        nomes.add("Ian");
        nomes.add("Inacio");
        nomes.add("Italo");
        nomes.add("Icaro");
        nomes.add("João");
        nomes.add("José");
        nomes.add("Jonathan");
        nomes.add("Jefferson");
        nomes.add("Jeremias");
        nomes.add("Kaue");
        nomes.add("Kaique");
        nomes.add("Kevin");
        nomes.add("Kelvin");
        nomes.add("Kennerson");
        nomes.add("Lucas");
        nomes.add("Leandro");
        nomes.add("Leonardo");
        nomes.add("Luan");
        nomes.add("Lauro");
        nomes.add("Matheus");
        nomes.add("Messias");
        nomes.add("Marlon");
        nomes.add("Maicon");
        nomes.add("Miguel");
        nomes.add("Nicolas");
        nomes.add("Nathan");
        nomes.add("Nicolau");
        nomes.add("Noak");
        nomes.add("Neanderson");
        nomes.add("Oliver");
        nomes.add("Otávio");
        nomes.add("Olavo");
        nomes.add("Otto");
        nomes.add("Osmar");
        nomes.add("Pedro");
        nomes.add("Paulo");
        nomes.add("Pietro");
        nomes.add("Piero");
        nomes.add("Pablo");
        nomes.add("Quintino");
        nomes.add("Quixote");
        nomes.add("Quincas");
        nomes.add("Quirino");
        nomes.add("Quirós");
        nomes.add("Ricardo");
        nomes.add("Roberto");
        nomes.add("Renato");
        nomes.add("Renan");
        nomes.add("Rodolfo");
        nomes.add("Silvio");
        nomes.add("Severino");
        nomes.add("Sérgio");
        nomes.add("Samuel");
        nomes.add("Saulo");
        nomes.add("Teodoro");
        nomes.add("Thales");
        nomes.add("Tadeu");
        nomes.add("Tunico");
        nomes.add("Travis");
        nomes.add("Ulisses");
        nomes.add("Ubiratan");
        nomes.add("Ubere");
        nomes.add("Uriel");
        nomes.add("Uziel");
        nomes.add("Victor");
        nomes.add("Vitor");
        nomes.add("Valter");
        nomes.add("Vinicius");
        nomes.add("Vanderlei");
        nomes.add("Xavier");
        nomes.add("Xisto");
        nomes.add("Xavi");
        nomes.add("Xerxes");
        nomes.add("Xabier");
        nomes.add("Wallyson");
        nomes.add("Wesley");
        nomes.add("Wendel");
        nomes.add("Wallace");
        nomes.add("Washington");
        nomes.add("Yan");
        nomes.add("Yuri");
        nomes.add("Ygor");
        nomes.add("Ysmael");
        nomes.add("Ycaro");
        nomes.add("Zaqueu");
        nomes.add("Ziraldo");
        nomes.add("Zacarias");
        nomes.add("Zyon");
        nomes.add("Zenon");
        return nomes;
}
    private List<String> lista_de_sobrenomes(){
        List<String> sobrenomes = new ArrayList();
        sobrenomes.add("Almeida");
        sobrenomes.add("Assis");
        sobrenomes.add("Andrade");
        sobrenomes.add("Alvarez");
        sobrenomes.add("Assunção");
        sobrenomes.add("Borges");
        sobrenomes.add("Bianchi");
        sobrenomes.add("Barolo");
        sobrenomes.add("Barbieri");
        sobrenomes.add("Bernardes");
        sobrenomes.add("Costa");
        sobrenomes.add("Cunha");
        sobrenomes.add("Castro");
        sobrenomes.add("Correia");
        sobrenomes.add("Conceição");
        sobrenomes.add("Damares");
        sobrenomes.add("Delgado");
        sobrenomes.add("Das Dores");
        sobrenomes.add("Danubio");
        sobrenomes.add("Dourado");
        sobrenomes.add("Elias");
        sobrenomes.add("Esperança");
        sobrenomes.add("Eufrades");
        sobrenomes.add("Ermelino");
        sobrenomes.add("Estácio");
        sobrenomes.add("Fraldino");
        sobrenomes.add("Fagundes");
        sobrenomes.add("Figueira");
        sobrenomes.add("Fonseca");
        sobrenomes.add("Figueiredo");
        sobrenomes.add("Gusmão");
        sobrenomes.add("Gutierrez");
        sobrenomes.add("Geraldi");
        sobrenomes.add("Gomes");
        sobrenomes.add("Gonzales");
        sobrenomes.add("Hernandez");
        sobrenomes.add("Herrera");
        sobrenomes.add("Henderson");
        sobrenomes.add("Hansen");
        sobrenomes.add("Hall");
        sobrenomes.add("Iglesias");
        sobrenomes.add("Ignácio");
        sobrenomes.add("Isgária");
        sobrenomes.add("Idalino");
        sobrenomes.add("Iki");
        sobrenomes.add("Jamelli");
        sobrenomes.add("Johnson");
        sobrenomes.add("Jaburu");
        sobrenomes.add("Jandir");
        sobrenomes.add("Jesus");
        sobrenomes.add("Kaiser");
        sobrenomes.add("Kanan");
        sobrenomes.add("Kappel");
        sobrenomes.add("Kampf");
        sobrenomes.add("Kalchik");
        sobrenomes.add("Lins");
        sobrenomes.add("Linhares");
        sobrenomes.add("Lopes");
        sobrenomes.add("Lima");
        sobrenomes.add("Leite");
        sobrenomes.add("Menezes");
        sobrenomes.add("Munhoz");
        sobrenomes.add("Matias");
        sobrenomes.add("Malaquias");
        sobrenomes.add("Monte");
        sobrenomes.add("Neves");
        sobrenomes.add("Navais");
        sobrenomes.add("Navarro");
        sobrenomes.add("Naves");
        sobrenomes.add("Noran");
        sobrenomes.add("Oliveira");
        sobrenomes.add("Ortiz");
        sobrenomes.add("Otero");
        sobrenomes.add("Oliva");
        sobrenomes.add("Olsen");
        sobrenomes.add("Pavão");
        sobrenomes.add("Pereira");
        sobrenomes.add("Pinto");
        sobrenomes.add("Portugal");
        sobrenomes.add("Pierri");
        sobrenomes.add("Quinteros");
        sobrenomes.add("Quitaúna");
        sobrenomes.add("Quintana");
        sobrenomes.add("Quevedo");
        sobrenomes.add("Quezada");
        sobrenomes.add("Reis");
        sobrenomes.add("Rossi");
        sobrenomes.add("Rios");
        sobrenomes.add("Rocha");
        sobrenomes.add("Ramires");
        sobrenomes.add("Ramos");
        sobrenomes.add("Silva");
        sobrenomes.add("Souza");
        sobrenomes.add("Silveira");
        sobrenomes.add("Santos");
        sobrenomes.add("Sanches");
        sobrenomes.add("Tahan");
        sobrenomes.add("Tellez");
        sobrenomes.add("Tramontina");
        sobrenomes.add("Torres");
        sobrenomes.add("Thompson");
        sobrenomes.add("Ugarte");
        sobrenomes.add("Umbelino");
        sobrenomes.add("Udson");
        sobrenomes.add("Uruguaiana");
        sobrenomes.add("Umbral");
        sobrenomes.add("Vasques");
        sobrenomes.add("Vilela");
        sobrenomes.add("Vieira");
        sobrenomes.add("Villasboas");
        sobrenomes.add("Vila");
        sobrenomes.add("Xavier");
        sobrenomes.add("Xuxa");
        sobrenomes.add("Xerxes");
        sobrenomes.add("Xiao");
        sobrenomes.add("Ximenez");
        sobrenomes.add("Yang");
        sobrenomes.add("Ybarra");
        sobrenomes.add("York");
        sobrenomes.add("Ye");
        sobrenomes.add("Yanes");
        sobrenomes.add("Ziraldi");
        sobrenomes.add("Zidani");
        sobrenomes.add("Zambrano");
        sobrenomes.add("Zamora");
        sobrenomes.add("Zapata");
        return sobrenomes;
    }
    private List<String> lista_de_apelidos(){
        List<String> apelidos = new ArrayList();
        apelidos.add("Aranha");
        apelidos.add("Alicate");
        apelidos.add("Amorzinho");
        apelidos.add("Arranca-toco");
        apelidos.add("Almeidão");
        apelidos.add("Baleia");
        apelidos.add("Betoneira");
        apelidos.add("Botafofo");
        apelidos.add("Brocador");
        apelidos.add("Bira");
        apelidos.add("Coelho");
        apelidos.add("Cospe-Chumbo");
        apelidos.add("Chupingole");
        apelidos.add("Comedor de casada");
        apelidos.add("Costinha");
        apelidos.add("Dino");
        apelidos.add("Dique Vigarista");
        apelidos.add("Dominante");
        apelidos.add("Deitaneles");
        apelidos.add("Dudão");
        apelidos.add("Esquilo");
        apelidos.add("Ergue Taça");
        apelidos.add("Enfiafofo");
        apelidos.add("Esquizofrênico");
        apelidos.add("Edu");
        apelidos.add("Foca");
        apelidos.add("Fogueirinha");
        apelidos.add("Fifi");
        apelidos.add("Franco-atirador");
        apelidos.add("Fepa");
        apelidos.add("Gorila");
        apelidos.add("Guina");
        apelidos.add("Garganta Profunda");
        apelidos.add("Gladiador");
        apelidos.add("Guga");
        apelidos.add("Hulk");
        apelidos.add("Hudini");
        apelidos.add("Iguana");
        apelidos.add("Ioio");
        apelidos.add("Jacaré");
        apelidos.add("Jhonny");
        apelidos.add("Jejeu");
        apelidos.add("Jantador");
        apelidos.add("Jojão");
        apelidos.add("Kamikazi");
        apelidos.add("Kamehameha");
        apelidos.add("Kico");
        apelidos.add("Lontra");
        apelidos.add("Ligeirinho");
        apelidos.add("Lambidinha");
        apelidos.add("Lampião");
        apelidos.add("Lula");
        apelidos.add("Macaco");
        apelidos.add("Maconheiro");
        apelidos.add("Mimoso");
        apelidos.add("Matador");
        apelidos.add("Mossoró");
        apelidos.add("Nequinha");
        apelidos.add("Nene");
        apelidos.add("Novinho");
        apelidos.add("Nabucodonosor");
        apelidos.add("Nem");
        apelidos.add("Orca");
        apelidos.add("Ombrinho");
        apelidos.add("Obá");
        apelidos.add("Piolho");
        apelidos.add("Pulga");
        apelidos.add("Puxa-trinco");
        apelidos.add("Perna Torta");
        apelidos.add("Piupiu");
        apelidos.add("Pimpolho");
        apelidos.add("Queixinho");
        apelidos.add("Queijadinha");
        apelidos.add("Queridinho");
        apelidos.add("Rato");
        apelidos.add("Ricochete");
        apelidos.add("Rancatripa");
        apelidos.add("Roludo");
        apelidos.add("Ratatá");
        apelidos.add("Silveirinha");
        apelidos.add("Sapo");
        apelidos.add("Saci");
        apelidos.add("Socafofo");
        apelidos.add("Sambafeio");
        apelidos.add("Tatu");
        apelidos.add("Traficante");
        apelidos.add("Tranca-Rua");
        apelidos.add("Tota");
        apelidos.add("Tchu-tchu");
        apelidos.add("157");
        apelidos.add("Uvinha");
        apelidos.add("Urso");
        apelidos.add("Ursinho");
        apelidos.add("Uiui");
        apelidos.add("Vassourinha");
        apelidos.add("Vemdefrente");
        apelidos.add("Vavá");
        apelidos.add("Vevé");
        apelidos.add("Xoxo");
        apelidos.add("Ximbinha");
        apelidos.add("Xitãozinho");
        apelidos.add("Xororó");
        apelidos.add("Xuxu");
        apelidos.add("Zé");
        apelidos.add("Zeca");
        apelidos.add("Zeza");
        apelidos.add("Zezinho");
        return apelidos;
    }
    private String nome_sorteado(List<String> nomes){ 
        int indiceAleatorio = random.nextInt(nomes.size());
        return nomes.get(indiceAleatorio);
 
    }
    private String sobrenome_sorteado(List<String> sobrenomes){ 
        int indiceAleatorio = random.nextInt(sobrenomes.size());
        return sobrenomes.get(indiceAleatorio);
    }
    private String apelidos(List<String> apelidos){ 
        int indiceAleatorio = random.nextInt(apelidos.size());
        return apelidos.get(indiceAleatorio);
    }
    private List<String> lista_de_sorteados(){
        List<String> sorteados = new ArrayList();
        List<String> nomes = lista_de_nomes();
        List<String> sobrenomes = lista_de_sobrenomes();
        List<String> apelidos = lista_de_apelidos();
        
        String nomeSorteado = nome_sorteado(nomes);
        String sobrenomeSorteado = sobrenome_sorteado(sobrenomes);
        String apelidoSorteado = apelidos(apelidos);
        
        sorteados.add("");
        sorteados.add(nomeSorteado);
        sorteados.add(sobrenomeSorteado);
        sorteados.add(apelidoSorteado);
        return sorteados;
    }
    
    private String sorteado_sorteado(List<String> sorteados){
        int IndiceAleatorio = random.nextInt(sorteados.size());
        return sorteados.get(IndiceAleatorio);
    }
    public String nome_final() {
    List<String> sorteados = lista_de_sorteados();
    
    // Sorteia o primeiro nome
    String sorteado_dos_sorteados1 = sorteado_sorteado(sorteados);
    
    // Sorteia o segundo nome até que seja diferente do primeiro
    String sorteado_dos_sorteados2;
    do {
        sorteado_dos_sorteados2 = sorteado_sorteado(sorteados);
    } while (sorteado_dos_sorteados2.equals(sorteado_dos_sorteados1));
    
    List<String> ListaDeSobrenomes = lista_de_sobrenomes();
    List<String> ListaDeApelidos = lista_de_apelidos();
    List<String> ListaDeNomes = lista_de_nomes();
    // Verifica se algum dos nomes sorteados é vazio e monta a string final corretamente
    String nomeFinal;
    if (sorteado_dos_sorteados1.isEmpty()) {
        nomeFinal = sorteado_dos_sorteados2;  // Só usa o segundo nome se o primeiro for vazio
    } else if (sorteado_dos_sorteados2.isEmpty()) {
        nomeFinal = sorteado_dos_sorteados1;  // Só usa o primeiro nome se o segundo for vazio
    } else if (ListaDeSobrenomes.contains(sorteado_dos_sorteados1) && ListaDeNomes.contains(sorteado_dos_sorteados2)){
        nomeFinal = sorteado_dos_sorteados2 + " " + sorteado_dos_sorteados1;
    }
    else if (ListaDeApelidos.contains(sorteado_dos_sorteados1) && ListaDeNomes.contains(sorteado_dos_sorteados2)) {
        nomeFinal = sorteado_dos_sorteados2 + " " + sorteado_dos_sorteados1;
    }  
      else {
        nomeFinal = sorteado_dos_sorteados1 + " " + sorteado_dos_sorteados2;  // Usa ambos com espaço
    }

    return nomeFinal;
}

}
